//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFinder.Resources.Strings
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordFinder.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string PlayGame => ResourceManager.GetString("PlayGame", resourceCulture);
        internal static string BestScore => ResourceManager.GetString("BestScore", resourceCulture);
        internal static string Settings => ResourceManager.GetString("Settings", resourceCulture);
        internal static string Vibrate => ResourceManager.GetString("Vibrate", resourceCulture);
        internal static string Sound => ResourceManager.GetString("Sound", resourceCulture);
        internal static string Dictionary => ResourceManager.GetString("Dictionary", resourceCulture);
        internal static string English => ResourceManager.GetString("English", resourceCulture);
        internal static string Ukrainian => ResourceManager.GetString("Ukrainian", resourceCulture);
        internal static string MainMenu => ResourceManager.GetString("MainMenu", resourceCulture);
        internal static string BuyPremiumVersion => ResourceManager.GetString("BuyPremiumVersion", resourceCulture);
        internal static string RestorePurchase => ResourceManager.GetString("RestorePurchase", resourceCulture);
        internal static string PremiumUpgradeMessage => ResourceManager.GetString("PremiumUpgradeMessage", resourceCulture);
        internal static string GameDuration => ResourceManager.GetString("GameDuration", resourceCulture);
        internal static string TenMinutes => ResourceManager.GetString("TenMinutes", resourceCulture);
        internal static string FiveMinutes => ResourceManager.GetString("FiveMinutes", resourceCulture);
        internal static string TwoMinutes => ResourceManager.GetString("TwoMinutes", resourceCulture);
        internal static string FreePlayMode => ResourceManager.GetString("FreePlayMode", resourceCulture);
        internal static string Answers => ResourceManager.GetString("Answers", resourceCulture);
        internal static string TimeLeft => ResourceManager.GetString("TimeLeft", resourceCulture);
        internal static string Next => ResourceManager.GetString("Next", resourceCulture);
        internal static string Hint => ResourceManager.GetString("Hint", resourceCulture);
        internal static string ExitGame => ResourceManager.GetString("ExitGame", resourceCulture);
        internal static string Yes => ResourceManager.GetString("Yes", resourceCulture);
        internal static string No => ResourceManager.GetString("No", resourceCulture);
        internal static string GameOver => ResourceManager.GetString("GameOver", resourceCulture);
        internal static string Score => ResourceManager.GetString("Score", resourceCulture);
        internal static string Freeplay => ResourceManager.GetString("Freeplay", resourceCulture);
        internal static string BestScoreGameOver => ResourceManager.GetString("BestScoreGameOver", resourceCulture);
        internal static string PremiumUpgradeMessageGameOver => ResourceManager.GetString("PremiumUpgradeMessageGameOver", resourceCulture);
        internal static string TryAgain => ResourceManager.GetString("TryAgain", resourceCulture);
        internal static string GameDurationGameOver => ResourceManager.GetString("GameDurationGameOver", resourceCulture);
        internal static string GameDurationFormat => ResourceManager.GetString("GameDurationFormat", resourceCulture);
        internal static string Only => ResourceManager.GetString("Only", resourceCulture);
        internal static string BestScoreTitle => ResourceManager.GetString("BestScoreTitle", resourceCulture);
        internal static string AnsweredTotal => ResourceManager.GetString("AnsweredTotal", resourceCulture);
        internal static string Play => ResourceManager.GetString("Play", resourceCulture);
        internal static string HowToPlay => ResourceManager.GetString("HowToPlay", resourceCulture);
        internal static string HowToPlay1 => ResourceManager.GetString("HowToPlay1", resourceCulture);
        internal static string HowToPlay2 => ResourceManager.GetString("HowToPlay2", resourceCulture);
        internal static string HowToPlay3 => ResourceManager.GetString("HowToPlay3", resourceCulture);
        internal static string SkipTheWord => ResourceManager.GetString("SkipTheWord", resourceCulture);
        internal static string GetAHint => ResourceManager.GetString("GetAHint", resourceCulture);
        internal static string Congratulations => ResourceManager.GetString("Congratulations", resourceCulture);
        internal static string NoWordsFree => ResourceManager.GetString("NoWordsFree", resourceCulture);
        internal static string NoWordsPremium => ResourceManager.GetString("NoWordsPremium", resourceCulture);
    }
}